server:
  address: 192.168.29.105
  port: 9000
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  cors:
    allow-credentials: true
    allowed-headers: '*'
    allowed-methods: GET, POST, PUT, DELETE
    allowed-origins: http://localhost:4200
  datasource:
    password: razdeepak
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/exam
    username: root
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      leak-detection-threshold: 2100
      maxLifetime: 2000000
      maximumPoolSize: 20
      minimumIdle: 1
      poolName: SpringBootJPAHikariCP
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dev.sbmail@gmail.com
    password: hnea deut sobh bpqj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#
#  main:
#    allow-circular-references: true